controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    use_sim_time: true
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: -0.5
      max_vel_x: 0.5
      max_vel_theta: 1.5
      critics:
        - dwb_critics::GoalAlignCritic
        - dwb_critics::PathAlignCritic
        - dwb_critics::ObstacleFootprintCritic
        - dwb_critics::TwirlingCritic
      GoalAlignCritic:
        scale: 0.02
      PathAlignCritic:
        scale: 0.04
      ObstacleFootprintCritic:
        scale: 0.05
        safety_radius: 0.1
      TwirlingCritic:
        scale: 0.01

        
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["${namespace}/left_wheel_joint"]
    right_wheel_names: ["${namespace}/right_wheel_joint"]
    
    wheel_separation: 0.3
    wheel_radius: 0.05

    use_stamped_vel: false
    
    # Publish to tf
    publish_rate: 50.0
    
    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    
    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0