controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    cmd_vel_topic: cmd_vel_unstamped
    publish_rate: 50.0
    cmd_vel_timeout: 0.5
    
    # Physical properties
    wheel_separation: 0.30
    wheel_radius: 0.05
    
    wheels_per_side: 1
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 0.5
        min_acceleration: -0.5
    
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -1.0
        has_acceleration_limits: true
        max_acceleration: 0.5
        min_acceleration: -0.5
    
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    
    enable_odom_tf: true
    publish_odom: true
    publish_odom_tf: true
    base_frame_id: base_link
    odom_frame_id: odom
    tf_frame_prefix: ""
    publish_limited_velocity: true
    use_stamped_vel: false