/**:
  ros__parameters:
    # Robot physical constraints
    max_linear_velocity: 0.3  # m/s
    min_linear_velocity: -0.3 # m/s
    max_angular_velocity: 1.5  # rad/s
    min_angular_velocity: -1.5 # rad/s
    
    # Scan parameters
    laser_min_range: 0.15
    laser_max_range: 3.5
    
    # SLAM parameters
    resolution: 0.05
    update_frequency: 5.0
    publish_period: 0.05
    
    # RL parameters
    observation_space:
      scan: true
      odom: true
      relative_goal: true
      local_map: true
      merged_map: true
    
    action_space:
      type: "continuous"  # or "discrete"
      linear_range: [-0.3, 0.3]
      angular_range: [-1.5, 1.5]
      
    reward_weights:
      goal_reached: 100.0
      collision: -100.0
      progress: 1.0
      smoothness: -0.1