slam_toolbox:
  ros__parameters:
    # Critical Parameters
    use_sim_time: true
    debug_logging: true
    mode: mapping

    # Queue and Buffer Management 
    processor_threads: 1                   # Reduce processing threads
    transform_timeout: 0.5                 # Reduced timeout
    tf_buffer_duration: 30.0
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss
    max_solver_time: 0.025                # Reduced solver time
    max_laser_range: 3.5
    minimum_time_interval: 0.5
    transform_publish_period: 0.05
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 3.5
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    stack_size_to_use: 40000000
    enable_interactive_mode: false

    # Advanced Processing
    use_scan_matching: false              # Disable scan matching temporarily
    use_scan_barycenter: false            # Disable barycenter
    scan_processing_thread_greedy: false  # Less aggressive processing
    laser_min_range: 0.15
    laser_max_range: 3.5